### ISSUE TITLE
New Byaml version found (v2)

### ISSUE THREAD

**Issue by OatmealDome** [Syroot/NintenTools.Byaml#2]
Interestingly, Nintendo incremented the Byaml version number for files of that type found in Breath of the Wild. There also seems to be a new node type (``0x22`` if I remember correctly). Example files are located in ``content/Map/MainField`` with a ``.smubin`` file extension. They are Yaz0 compressed.

**Comment by RayKoopa** [comment]
Not sure when I come to that. If you want to decompress Yaz0, you can use https://github.com/Syroot/NintenTools.Yaz0 - though I also never got the interest to put in a compression routine (other libs might provide that).

**Comment by Warpten** [comment]
A few couple nodes have emerged, namely `0x8c` and `0xd3`. I went on the assumption that `0xd3` is just a long, which seems to work, but `0x8c` is probably a full node that requires more work - such as looking into it in PPC assembly. I'm doing that right now.

**Comment by RayKoopa** [comment]
I am currently rewriting the library (and actually trashing the serialization features as they are simply not worth the performance loss and my time), but I do not have access to those files. Is it possible to get them anywhere to look into them?

**Comment by OatmealDome** [comment]
I can upload a few BoTW byaml files if needed, though I suppose that I would be violating Nintendo's copyright...

**Comment by RayKoopa** [comment]
Definitely; do you have Discord by any chance? Though I became busy with documenting the BFRES remainders, so it can wait from my side.

**Comment by OatmealDome** [comment]
Yeah, I do. Here's my tag: OatmealDome#2837

**Comment by RayKoopa** [comment]
The `content/Map/MainField/DebugDemoArea.smubin` file you mentioned only says it is version 2, I did not find any new node types in it. Do you have exact sample files containing those new nodes?

**Comment by RayKoopa** [comment]
Already implemented in the upcoming 3.0.0 version of the library.
