### ISSUE TITLE
Need help, VS 2017 wont work properly.

### ISSUE THREAD

**Issue by PedrolinoV2** [Syroot/NintenTools.Byaml#3]
Sorry to bother, but I was trying to use this on a Splatoon .byaml but I dont even know were to start.
If you can help me, I appreciate it.

**Comment by RayKoopa** [comment]
The [wiki](https://github.com/Syroot/NintenTools.Byaml/wiki) contains all the information on how to use the library. If you have specific issues with a single feature, please explain this _detailledly_ in a new issue.

**Comment by RayKoopa** [comment]
I think I understand what you meant now. You do not need to open the solution and download the source (if you want to compile from source, you'd need .NET Core tooling to be installed). You should download the NuGet package into your project, as stated on the main page and the wiki.
